on:
  workflow_call:
    secrets:
      infracost_api_key:
        required: true
env:
      working-directory: /infracost_demo
      AWS_REGION: eu-central-1
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}        
jobs:
  infracost:
    runs-on: ubuntu-latest
    env:
       DEPLOYMENT_ENV: "dev"

    name: Run Infracost
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}    
      - name: Run Infracost action
        uses: Liquid-Reply/demo-actions/infracost@main
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}