on:
  workflow_call:
    secrets:
      infracost_api_key:
        required: true
env:
      AWS_REGION: eu-central-1
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}        
jobs:
  infracost:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     pull-requests: write
     id-token: write
    env:
       DEPLOYMENT_ENV: "dev"

    name: Run Infracost
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'   
      - name: Run Infracost action
        uses: Liquid-Reply/demo-actions/infracost@main
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 